# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: magentic-ui项目demo

on:
  schedule:
    # 此处是UTC时间，对应北京时间早八点
    - cron : '00 00 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: docker:latest
    services:
      docker:
        image: docker:dind
        env:
          DOCKER_TLS_CERTDIR: ""

    steps:
    # checkout仓库
    - uses: actions/checkout@v3
    # 设置Python版本
    - name: Set up Python 3.11.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.9"
    # 更新cache: "pip"
    - name: Upgrade pip
      run: |
        pip install --upgrade pip
    # 安装uv
    - name: Install uv
      run: |
        pip install uv
    # 安装依赖
    - name: Install dependencies with uv
      run: |
        uv sync
    # 运行项目
    - name: Run magentic-ui with uv
      run: |
        magentic ui --port 8081
      env:
        OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}