[project]
name = "gihub-action-sanyaosa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "magentic-ui>=0.0.4",
    "requests>=2.32.3",
]
