[project]
name = "gihub-action-sanyaosa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.3",
    "wxauto>=3.9.11.17.5",
]
